### ISSUE TITLE
Error 6 when Updating GeoIP country database

### ISSUE THREAD

**Issue by SteamsDev** [MustaphaTR/Generals-Alpha#12]
I've been trying to build Generals-Alpha on a Linux system for a while now and it always seems to stop at the point where it is trying to update the GeoIP country database. Every time I try it game me the following error.
`$ make`
`make[1]: Entering directory '/home/SteamsDev/generals-alpha/Generals-Alpha/generals-alpha-engine'`
`Updating GeoIP country database from MaxMind.`
`make[1]: *** [Makefile:319: geoip-dependencies] Error 6`
`make[1]: Leaving directory '/home/SteamsDev/generals-alpha/Generals-Alpha/generals-alpha-engine'`
`make: *** [Makefile:52: engine] Error 2`

Any help is appreciated. I have a Debian system.

**Comment by MustaphaTR** [comment]
Recent changes to GeoIP stuff has caused all the mods to break down on Linux and considering this mod is pretty much dead for me, i'm not sure if i'm gonna bother fixing this.

**Comment by SteamsDev** [comment]
Okay. It looks like this applies to all OpenRA mods that need to be built through the terminal. I might start a pull request on OpenRA/ra2 and see if there is a solution to it, given we can still get the GeoIP database.

I guess I should also mention that I have a limited internet connection at home. I might try again on my school's internet and get back to you when I can.
