### ISSUE TITLE
USA SpySat Timer too short

### ISSUE THREAD

**Issue by SteamsDev** [MustaphaTR/Generals-Alpha#4]
I don't know if you noticed already, but the SpySat timer for USA is way too short. For me the cooldown timer is 7 seconds. Could you possibly fix that so it's not spammed all the time? Thanks!

**Comment by MustaphaTR** [comment]
It is actually 1 minute on normal. You probably opened the game on SuperFast. Game Speed selection effects what timers show.

SuperFast is there just for fun, don't consider it for a normal gameplay.

**Comment by SteamsDev** [comment]
Ah, makes sense. Thanks.
