### ISSUE TITLE
USA Intelligence affects other players

### ISSUE THREAD

**Issue by SteamsDev** [MustaphaTR/Generals-Alpha#6]
I've encountered a bug related to USA: I was doing a game as USA against another USA and a PRC, and I found out that the AI USA's Intelligence still had an effect on me even though he was an enemy. Because of that I could see the entire PRC base without needing my Intelligence. I figured maybe that wasn't intended.
![openra-2018-02-23t014614186z](https://user-images.githubusercontent.com/20361090/36634204-f8cdb2c4-196e-11e8-89ce-e9e3ee681bfa.png)
As you can see my intelligence still had 11 seconds left to recharge, and yet I had a similar experience to the Intelligence by being able to see the entire PRC base.

**Comment by MustaphaTR** [comment]
Known issue. intelligence currently give vision of your enemies to everyone, not just you (so it works as intented in a 2 team game, but not anything higher). I probably need a special trait for it, currently it work pretty hacky with map wide proximity conditions and enemy only `RevealsShroud:`s that get enabled by this.
