### ISSUE TITLE
error CS0414: Warning as Error: The private field `OpenRA.Mods.Common.Activities.EnterSharedTransport.maxTries' is assigned but its value is never used

### ISSUE THREAD

**Issue by fusion809** [MustaphaTR/Generals-Alpha#9]
Hi,

I managed to try to build early commits of this repository fine on openSUSE Tumbleweed, but the latest one fails with the error:

```bash
OpenRA.Mods.Common/Activities/EnterSharedTransport.cs(21,16): error CS0414: Warning as Error: The private field `OpenRA.Mods.Common.Activities.EnterSharedTransport.maxTries' is assigned but its value is never used
```

some of the previous lines of output were:

```bash
Detected Lua 5.1 library at /usr/lib64/liblua5.1.so.5.1
Eluant.dll.config has been created successfully.
CSC fixheader.exe
CSC OpenRA.Game.exe
CSC OpenRA.Platforms.Default.dll
CSC mods/common/OpenRA.Mods.Common.dll
```

running `make clean` also returned this error. 

Thanks for your time,
Brenton

**Comment by MustaphaTR** [comment]
Linux is annoyingly errors small issues like that which don't even give a warning on windows. I keep fixing these for later to not create multipile version numbers of same date, but considering current version number is last Friday (even tho i uploaded it today) i can fix that, give me some time.

I can see those errors as Travis checks fail.

**Comment by MustaphaTR** [comment]
Should work now.
